
package de.pubflow.components.jiraConnector.wsArtifacts;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IJiraEndpoint", targetNamespace = "http://webservice.jira.pubflow.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IJiraEndpoint {


    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createIssue", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.CreateIssue")
    @ResponseWrapper(localName = "createIssueResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.CreateIssueResponse")
    public long createIssue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        de.pubflow.components.jiraConnector.wsArtifacts.CreateIssue.Arg3 arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createIssueType", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.CreateIssueType")
    @ResponseWrapper(localName = "createIssueTypeResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.CreateIssueTypeResponse")
    public String createIssueType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        de.pubflow.components.jiraConnector.wsArtifacts.CreateIssueType.Arg2 arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeStatus", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.ChangeStatus")
    @ResponseWrapper(localName = "changeStatusResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.ChangeStatusResponse")
    public boolean changeStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addIssueComment", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.AddIssueComment")
    @ResponseWrapper(localName = "addIssueCommentResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.AddIssueCommentResponse")
    public boolean addIssueComment(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatusNames", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.GetStatusNames")
    @ResponseWrapper(localName = "getStatusNamesResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.GetStatusNamesResponse")
    public List<String> getStatusNames(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProject", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.CreateProjectResponse")
    public boolean createProject(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "appendFile", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.AppendFile")
    @ResponseWrapper(localName = "appendFileResponse", targetNamespace = "http://webservice.jira.pubflow.de/", className = "de.pubflow.jira.webservice.AppendFileResponse")
    public boolean appendFile(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
