
package de.pubflow.components.jiraConnector.wsArtifacts;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JiraEndpointService", targetNamespace = "pubflow.de", wsdlLocation = "https://localhost:8890/JiraEndpoint?wsdl")
public class JiraEndpointService
    extends Service
{

    private final static URL JIRAENDPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.pubflow.components.jiraConnector.wsArtifacts.JiraEndpointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.pubflow.components.jiraConnector.wsArtifacts.JiraEndpointService.class.getResource(".");
            url = new URL(baseUrl, "https://localhost:8890/JiraEndpoint?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://localhost:8890/JiraEndpoint?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        JIRAENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public JiraEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JiraEndpointService() {
        super(JIRAENDPOINTSERVICE_WSDL_LOCATION, new QName("pubflow.de", "JiraEndpointService"));
    }

    /**
     * 
     * @return
     *     returns JiraEndpoint
     */
    @WebEndpoint(name = "JiraEndpointPort")
    public JiraEndpoint getJiraEndpointPort() {
        return super.getPort(new QName("pubflow.de", "JiraEndpointPort"), JiraEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JiraEndpoint
     */
    @WebEndpoint(name = "JiraEndpointPort")
    public JiraEndpoint getJiraEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("pubflow.de", "JiraEndpointPort"), JiraEndpoint.class, features);
    }

}
