
package de.pubflow.components.jiraConnector.wsArtifacts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PubFlowToJiraConnectorService", targetNamespace = "http://webservice.jira.pubflow.de/", wsdlLocation = "http://localhost:8889/PubFlowToJiraConnector?wsdl")
public class PubFlowToJiraConnectorService
    extends Service
{

    private final static URL PUBFLOWTOJIRACONNECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBFLOWTOJIRACONNECTORSERVICE_EXCEPTION;
    private final static QName PUBFLOWTOJIRACONNECTORSERVICE_QNAME = new QName("http://webservice.jira.pubflow.de/", "PubFlowToJiraConnectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8889/PubFlowToJiraConnector?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBFLOWTOJIRACONNECTORSERVICE_WSDL_LOCATION = url;
        PUBFLOWTOJIRACONNECTORSERVICE_EXCEPTION = e;
    }

    public PubFlowToJiraConnectorService() {
        super(__getWsdlLocation(), PUBFLOWTOJIRACONNECTORSERVICE_QNAME);
    }

    public PubFlowToJiraConnectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBFLOWTOJIRACONNECTORSERVICE_QNAME, features);
    }

    public PubFlowToJiraConnectorService(URL wsdlLocation) {
        super(wsdlLocation, PUBFLOWTOJIRACONNECTORSERVICE_QNAME);
    }

    public PubFlowToJiraConnectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBFLOWTOJIRACONNECTORSERVICE_QNAME, features);
    }

    public PubFlowToJiraConnectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PubFlowToJiraConnectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPubFlowToJiraConnector
     */
    @WebEndpoint(name = "PubFlowToJiraConnectorPort")
    public IPubFlowToJiraConnector getPubFlowToJiraConnectorPort() {
        return super.getPort(new QName("http://webservice.jira.pubflow.de/", "PubFlowToJiraConnectorPort"), IPubFlowToJiraConnector.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPubFlowToJiraConnector
     */
    @WebEndpoint(name = "PubFlowToJiraConnectorPort")
    public IPubFlowToJiraConnector getPubFlowToJiraConnectorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.jira.pubflow.de/", "PubFlowToJiraConnectorPort"), IPubFlowToJiraConnector.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBFLOWTOJIRACONNECTORSERVICE_EXCEPTION!= null) {
            throw PUBFLOWTOJIRACONNECTORSERVICE_EXCEPTION;
        }
        return PUBFLOWTOJIRACONNECTORSERVICE_WSDL_LOCATION;
    }

}
